package tvkb.pig.gui;

import javax.swing.*;
import java.awt.*;

public class GameGUI
{
	protected JPanel    main;
	protected JTable    table;
	protected JButton   continueButton;
	protected JButton   saveButton;
	protected JButton   betButton;
	protected JTextPane textPane;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		main = new JPanel();
		main.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		main.setMinimumSize(new Dimension(-1, -1));
		main.setPreferredSize(new Dimension(-1, -1));
		final JSplitPane splitPane1 = new JSplitPane();
		splitPane1.setDividerLocation(400);
		splitPane1.setDividerSize(1);
		main.add(splitPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(300, -1), new Dimension(200, 200), null, 0, false));
		final JSplitPane splitPane2 = new JSplitPane();
		splitPane2.setDividerLocation(587);
		splitPane2.setDividerSize(1);
		splitPane2.setLastDividerLocation(0);
		splitPane2.setOrientation(0);
		splitPane2.setResizeWeight(1.0);
		splitPane1.setLeftComponent(splitPane2);
		table = new JTable();
		table.setFocusable(false);
		table.setInheritsPopupMenu(false);
		table.setIntercellSpacing(new Dimension(20, 20));
		table.setMaximumSize(new Dimension(-1, -1));
		table.setMinimumSize(new Dimension(300, -1));
		table.setOpaque(false);
		table.setPreferredScrollableViewportSize(new Dimension(450, 100));
		table.setRequestFocusEnabled(false);
		table.setRowHeight(40);
		splitPane2.setLeftComponent(table);
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
		panel1.setAlignmentY(0.5f);
		panel1.setAutoscrolls(true);
		panel1.setDoubleBuffered(true);
		panel1.setInheritsPopupMenu(false);
		panel1.setMinimumSize(new Dimension(300, 150));
		splitPane2.setRightComponent(panel1);
		continueButton = new JButton();
		continueButton.setMaximumSize(new Dimension(-1, -1));
		continueButton.setMinimumSize(new Dimension(300, 50));
		continueButton.setPreferredSize(new Dimension(-1, 50));
		continueButton.setText("Continue");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		panel1.add(continueButton, gbc);
		saveButton = new JButton();
		saveButton.setMaximumSize(new Dimension(-1, 50));
		saveButton.setMinimumSize(new Dimension(300, 50));
		saveButton.setPreferredSize(new Dimension(300, 50));
		saveButton.setText("Save");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		panel1.add(saveButton, gbc);
		betButton = new JButton();
		betButton.setMaximumSize(new Dimension(-1, -1));
		betButton.setMinimumSize(new Dimension(300, 50));
		betButton.setPreferredSize(new Dimension(300, 50));
		betButton.setText("Bet");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		panel1.add(betButton, gbc);
		final JScrollPane scrollPane1 = new JScrollPane();
		splitPane1.setRightComponent(scrollPane1);
		textPane = new JTextPane();
		textPane.setBackground(new Color(-12960960));
		textPane.setEditable(false);
		textPane.setEnabled(true);
		textPane.setFocusable(false);
		textPane.setForeground(new Color(-12960960));
		textPane.setMinimumSize(new Dimension(300, 300));
		textPane.setOpaque(true);
		scrollPane1.setViewportView(textPane);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return main;
	}
}
